version: "2.0"
language: zh
pipeline:
- name: SpacyNLP
  model: zh_core_web_md
- name: SpacyTokenizer
- name: SpacyFeaturizer
- name: RegexFeaturizer
- name: DIETClassifier
  epochs: 200
- name: EntitySynonymMapper
- name: RegexEntityExtractor
- name: ResponseSelector
  epochs: 100
- name: FallbackClassifier
  threshold: 0.5
  ambiguity_threshold: 0.2
policies:
- name: AugmentedMemoizationPolicy
- name: TEDPolicy
  epochs: 40
- name: RulePolicy
  core_fallback_threshold: 0.4
  core_fallback_action_name: "action_default_fallback"
  enable_fallback_prediction: True
