# debugMode enables / disables the debug mode for Rasa and Rasa X
debugMode: "set_as_environment_variable-RASAX_DEBUG_MODE"
# nginx ingress controller
nginx:
    service:
        port: 80
# docker pull secret for private images
images:
    imagePullSecrets:
    - name: "gcr-pull-secret"
    - name: "ecr-pull-secret"
# action server image
app:
    name: "set_as_environment_variable-APP_NAME"
    tag: "set_as_environment_variable-APP_TAG"
# rasax specific settings
rasax:
    tag: "set_as_environment_variable-RASAX_TAG"
    # name of the Rasa Enterprise image to use
    name: "gcr.io/rasa-platform/rasa-x-ee"
    # initialUser is the user which is created upon the initial start of Rasa Enterprise
    initialUser:
        # username specifies a name of this user
        username: "set_as_environment_variable-RASAX_INITIALUSER_USERNAME"
        # password for the Rasa Enterprise user
        password: "set_as_environment_variable-RASAX_INITIALUSER_PASSWORD"
    # passwordSalt Rasa X uses to salt the user passwords
    passwordSalt: "set_as_environment_variable-RASAX_PASSWORDSALT"
    # token Rasa X accepts as authentication token from other Rasa services
    token: "set_as_environment_variable-RASAX_TOKEN"
    # jwtSecret which is used to sign the jwtTokens of the users
    jwtSecret: "set_as_environment_variable-RASAX_JWTSECRET"
# rasa: Settings common for all Rasa containers
rasa:
    tag: "set_as_environment_variable-RASA_TAG"
    # token Rasa accepts as authentication token from other Rasa services
    token: "set_as_environment_variable-RASA_TOKEN"
    livenessProbe:
        # initialProbeDelay for the `livenessProbe`
        initialProbeDelay: 60
# RabbitMQ specific settings
rabbitmq:
    # rabbitmq settings of the subchart
    rabbitmq:
        # password which is used for the authentication
        password: "set_as_environment_variable-RABBITMQ_RABBITMQ_PASSWORD"
# global settings of the used subcharts
global:
    # postgresql: global settings of the postgresql subchart
    postgresql:
        # postgresqlPassword is the password which is used when the postgresqlUsername equals "postgres"
        postgresqlPassword: "set_as_environment_variable-GLOBAL_POSTGRESQL_POSTGRESQLPASSWORD"
    # redis: global settings of the redis subchart
    redis:
        # password to use in case there no external secret was provided
        password: "set_as_environment_variable-GLOBAL_REDIS_PASSWORD"